import { useQuery } from "@apollo/client/react";
import { AlertCircle } from "lucide-react";
import { PageLoading } from "@/components/ui/page-loading";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { GET_STOCK_MOVEMENTS_QUERY } from "@/graphql/mutations/stock.mutations";
import type { StockMovementsQueryResult } from "@/types/stock.types";
import { usePagination } from "@/hooks/usePagination";

export default function StockMovementsPage() {
  const { skip, take } = usePagination({ defaultPageSize: 20 });

  const {
    data: movementsData,
    loading,
    error,
  } = useQuery<StockMovementsQueryResult>(GET_STOCK_MOVEMENTS_QUERY, {
    variables: { pagination: { skip, take } },
    fetchPolicy: "cache-and-network",
  });

  if (loading) {
    return <PageLoading message="Loading stock movements..." />;
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-red-500">
        <AlertCircle className="h-8 w-8 mb-2" />
        <p>Failed to load stock movements</p>
      </div>
    );
  }

  const movements = movementsData?.stockMovements ?? [];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-slate-900">Stock Movements</h1>
        <p className="text-slate-600 mt-1">
          Read-only ledger of stock operations generated by warehouse workflows.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recent Movements</CardTitle>
        </CardHeader>
        <CardContent>
          {movements.length === 0 ? (
            <p className="text-sm text-slate-500">No stock movements yet.</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Product</TableHead>
                  <TableHead>Warehouse</TableHead>
                  <TableHead>Quantity</TableHead>
                  <TableHead>Operator</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {movements.map((movement) => (
                  <TableRow key={movement.id}>
                    <TableCell>
                        {new Date(movement.createdAt).toLocaleString()}
                    </TableCell>
                    <TableCell>{movement.type}</TableCell>
                    <TableCell>
                        {movement.product.sku} - {movement.product.name}
                    </TableCell>
                    <TableCell>{movement.warehouse.code}</TableCell>
                    <TableCell>{movement.quantity}</TableCell>
                    <TableCell>
                        {movement.createdBy.firstName} {movement.createdBy.lastName}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
